---

- name: Ensure terraform init
  ansible.builtin.command:
    cmd: "{{ set_and_check_facts_from_terraform_state_terraform_command }} init"
    creates: .terraform/terraform.tfstate
  delegate_to: localhost

- name: Ensure terraform state loaded
  ansible.builtin.command:
    cmd: "{{ set_and_check_facts_from_terraform_state_terraform_command }} show -json"
  register: _terraform_state_output
  changed_when: false
  delegate_to: localhost

- name: Set fact _terraform_state
  ansible.builtin.set_fact:
    _terraform_state: "{{ _terraform_state_output.stdout }}"
  delegate_to: localhost

- name: Ensure lookup required environment variables
  ansible.builtin.set_fact: { 
    "{{ item }}": "{{ _terraform_state 
      | community.general.json_query('values.outputs.'+item+'.value')
    }}" 
  }
  loop: "{{ set_and_check_facts_from_terraform_state_required_vars }}"
  delegate_to: localhost

...